history.section.title=Anciennes versions
type.feature.title=Features 💰
type.fix.title=Corrections 🩹
type.refactor.title=Refactorings 🚀
type.build.title=Dépendances, versions, CI, etc. ⚙️
type.ops.title=Infra, déploiement, etc. 📡
type.style.title=Style ✂️
type.doc.title=Documentation 📜
type.chore.title=Divers



quarkus.qute.suffixes=adoc
quarkus.log.category."com.kawamind".min-level=TRACE

%test.quarkus.log.category."com.kawamind".level=TRACE